# SPDX-License-Identifier: GPL-3.0-or-later
# Build and validate the Inversée Flatpak on every push and pull request.

name: Flatpak

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: inversee.flatpak
          manifest-path: build-aux/fr.benjaminbellamy.Inversee.yml
          cache-key: flatpak-builder-${{ github.sha }}
          run-tests: true
